# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.19

    steps:
      - checkout


  deploy:
    docker:
      - image: cimg/go:1.19

    steps:
      - checkout
          fetch-depth: 0
      - run:
          name: Release if new version
          command: |
            export shvar1=$(git tag)
            export shvar2=$(ls -la .git)
            export tagvalue=$(git tag | grep ${version})
            echo '============= print 1 & 2 ======'
            echo $shvar1
            echo $shvar2
            echo '======== print 3 =========='
            echo '========'
            echo $tagvalue
            echo '============='
            
          
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires: 
            - build
